version: '3'

services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome
    volumes:
      - data:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
